# Generated by Django 5.0.6 on 2024-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_commentpost_comment_count_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(default='profile_image/Screenshot_from_2024-05-13_12-39-29.png', upload_to='profile_image/'),
        ),
    ]
